export const SET_CITY_DATA = 'SET_CITY_DATA';
export const CHANGE_CURRENT_CITY = 'CHANGE_CURRENT_CITY';
export const GET_HEADER_HEIGHT = 'GET_HEADER_HEIGHT';
export const CHANGE_PATH_ROUTER = 'CHANGE_PATH_ROUTER';
